### ISSUE TITLE
panic: expected Integer fromIntModOp

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/saw-core#145]
This short SAWscript file

    let {{
    type t_Fp = Z 1001

    to_mont: t_Fp -> t_Fp
    to_mont x = x * 512

    type Fp_rep_t = [2][8]

    from_Fp: t_Fp -> [16]
    from_Fp x = fromInteger (fromZ x)

    fp_rep: t_Fp -> Fp_rep_t
    fp_rep x =  reverse (split (from_Fp (to_mont x)))
    }};

    prove z3 {{ fp_rep 123 == [0x92, 0x03] }};

causes problems in a recent build of SAW

    %< --------------------------------------------------- 
       Revision:  d52a05c690929bd5ec9d9e27ef0f0674feca40d4
       Branch:    HEAD (uncommited files present)
       Location:  Verifier.SAW.Simulator.Prims
       Message:   expected Integer fromIntModOp
    CallStack (from HasCallStack):
       panic, called at src/Verifier/SAW/Utils.hs:37:9 in saw-core-0.1-inplace:Verifier.SAW.Utils
       panic, called at src/Verifier/SAW/Simulator/Prims.hs:268:13 in saw-core-0.1-inplace:Verifier.SAW.Simulator.Prims
       panic, called at src/Verifier/SAW/Simulator/Prims.hs:298:15 in saw-core-0.1-inplace:Verifier.SAW.Simulator.Prims
    %< ---------------------------------------------------

**Comment by brianhuffman** [comment]
The what4 and SBV-based backends both lead to the same error. Apparently this is exactly the same issue as #109, but in other backends. I should have checked for this when I fixed the other one.
