### ISSUE TITLE
Internal type error

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/saw-core#147]
This SAWscript

    let {{
      bv_to_Z: {n} (fin n) => [n] -> Z (2^^n)
      bv_to_Z x = fromInteger (toInteger x)
      }};

    prove z3 {{ \ (x:[4]) y -> bv_to_Z (x+y) == ((bv_to_Z x) + (bv_to_Z y)) }};

results in

    You have encountered a bug in cryptol-saw-core's implementation.
    *** Please create an issue at https://github.com/GaloisInc/saw-core/issues

    %< --------------------------------------------------- 
      Revision:  d52a05c690929bd5ec9d9e27ef0f0674feca40d4
      Branch:    HEAD (uncommited files present)
      Location:  proveEq
      Message:   Internal type error:
                 Z (2 ^^ 4)
                 Z 16
    CallStack (from HasCallStack):
      panic, called at src/Verifier/SAW/Cryptol/Panic.hs:13:9 in cryptol-saw-core-0.1-inplace:Verifier.SAW.Cryptol.Panic
      panic, called at src/Verifier/SAW/Cryptol.hs:1363:9 in cryptol-saw-core-0.1-inplace:Verifier.SAW.Cryptol
    %< ---------------------------------------------------

**Comment by brianhuffman** [comment]
It looks like there is a missing case in the type-equality solver in `cryptol-saw-core`. Apparently this function was not updated properly when the `Z` type was added. It should be easy to fix.
