### ISSUE TITLE
Add a sort "Prop"?

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-core#15]
We should decide whether to add a sort `Prop` to SAWCore. This could give us a few benefits, e.g. we could limit the set of types at which we are allowed to use recursion, or it could let us do a more principled form type erasure in the evaluation backends.

**Comment by robdockins** [comment]
I'm in favor of a separate `Prop` sort.  It puts us on a path toward segregating general recursion and partiality, which is important if we want to take the programs-as-proofs paradigm seriously.  It also  forces us to be careful about the difference between, say `Bool`, a (partial?) boolean computation and `Prop`, a logical proposition admitting the possibility of proof.  I think this a valuable distinction.

**Comment by kiniry** [comment]
+1
