### ISSUE TITLE
saw-core tests broken in 9dfb209

### ISSUE THREAD

**Issue by kquick** [GaloisInc/saw-core#151]
A rewriter test indicates unexpected results and causes a test failure for saw-core.  

```
                           [fails]
              +---[PR118]--9dfb209--145e831--3384748--f93b018--+
             /                                                  \
            /     [passes]                                       \
13995d8 ---*------30f26cd---------------------------------------db41a9b--...->HEAD
[passes]           /                                            [fails]
                  /
---[PR120]-------/
```

It may simply be that the expected output from the test needs to be updated, but it's not obvious that this is the case.

**Comment by brianhuffman** [comment]
I know what the problem is. PR #118 was supposed to uniformly change the way all saw-core code constructed constant terms, except the `Conversion` module still uses a lower-level function that still builds constant terms in the old way.
