### ISSUE TITLE
Hurken's paradox

### ISSUE THREAD

**Issue by m-yac** [GaloisInc/saw-core#171]
SAWCore permits the following datatype:
```
data Sort : sort 0 where {
  in : sort 0 -> Sort;
}
```
which can be used to prove `EqP Bool True False` - see this gist: https://gist.github.com/m-yac/e5cc427e2e0db2e79d0fd14543664941

The one caveat is that I only tested this on the `wip-heapster` branch of `saw-script`, since I don't know how to typecheck a SAWCore file on `master`. (On `wip-heapster`, I used `load_sawcore_from_file`.)

**Comment by brianhuffman** [comment]
What's the proposed fix for this? I suppose that this data definition should only be accepted if we changed it to `data Sort : sort 1`, or some other universe that is strictly larger than `sort 0`?

**Comment by eddywestbrook** [comment]
This is probably just a simple bug in Typechecker.hs. Looking for it now...

**Comment by m-yac** [comment]
> I suppose that this data definition should only be accepted if we changed it to `data Sort : sort 1`, or some other universe that is strictly larger than `sort 0`?

Yep. For example, I believe Agda ensures that universe level of an inductive type is always greater than the level of any universe that appears in its constructors.

**Comment by eddywestbrook** [comment]
I just tested a fix for this. I wasn’t sure what to do with it, so I pushed it to the wip-heapster branch, since we are cherry-picking its commits anyway. The commit is 8df33bb.

**Comment by eddywestbrook** [comment]
Whoops, this exposed a bug in the definition of LetRecTypes in the prelude, which is where Matt originally found it. The commit for that is 63814bb.
