### ISSUE TITLE
Some instances of `atWithDefault` aren't being evaluated

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-core#24]
Many of the tests in the `jvm-verifier` and `llvm-verifier` packages are currently failing because an expression they expect to evaluate to a concrete value is remaining symbolic. I believe this is a case of the new `atWithDefault` function not being evaluated in some cases, even when it has concrete arguments.

**Comment by brianhuffman** [comment]
This is probably the fault of the conversion library; we have a conversion for rewriting applications of `at`, but I haven't implemented one for `atWithDefault`.
