### ISSUE TITLE
Use something besides `s` type parameter to prevent making ill-formed SharedTerms

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-core#25]
Values of type `SharedTerm` contain `TermIndex` (i.e. `Int`) values to permit observable sharing. Here's the datatype invariant: If a `SharedTerm` contains two subterms with the same `TermIndex`, then those subterms must be equal.

Currently we use a counter in the `SharedContext` as a supply of unique `TermIndex`es. If someone were to combine terms built from two different `SharedContext`s, it is possible that two different subterms might end up with the same `TermIndex`, which would violate the invariant.

To prevent this from happening, `SharedTerm` and `SharedContext` have a type parameter `s` that can be used to distinguish different `SharedContext`s by type. But currently this doesn't work: Using `mkSharedContext :: Module -> IO (SharedContext s)`, it is possible to create multiple `SharedContext`s with the same type. To make it work properly, we would have to switch to something like `withSharedContext :: Module -> (forall s. SharedContext s -> IO a) -> IO a`. But this would then mean adding a parameter `s` to dozens of other related types, and also using rank-2-typed "with" functions for any monads that use a `SharedContext`. Things get ugly.

@robdockins and I have found another, simpler, solution to the same problem: `StableName`s. Instead of generating a `TermIndex` from a per-`SharedContext` counter, we just generate a `StableName` for each term to use as the `TermIndex`. (`StableName`s are generated in the `IO` monad.) Unlike the `Int` counters, `StableName`s are guaranteed to be globally unique, even for terms built in different `SharedContext`s.

This means that it's perfectly OK to combine terms that were constructed in different `SharedContext`s; in fact it might be desirable to do so if we want to use a different hash-consing strategy in different situations, or if we want to make a temporary hash-consing table that we throw away when we are done with it. And since we don't have to worry about segregating terms from different `SharedContext`s, we don't have any need for the annoying type parameter `s`.

**Comment by atomb** [comment]
I was just talking with @brianhuffman about this, and I think it's a compelling argument to have a global name supply instead of a local one associated with each `SharedContext`. It's possible that some other library, such as `value-supply`, could serve the role of generating fresh values. But the `StableName` type could also very well be a good approach.

**Comment by joehendrix** [comment]
I think a `StableName` approach should be fine, although I don't find the extra type parameter all that ugly.  The two advantages in my opinion of it are:

 * `StableName` require the `IO` monad whereas the type parameter can work with 'ST'.
 * The extra type parameter can help enforce consistency checks (e.g., if you want to ensure terms between different shared contexts aren't mixed for some other reason, such as ensuring all shared terms use the same hash cons database).

If neither of these are concerns, then `StableName` is less work.

As a side note, in addition to use of `with`-style functions functions, you can also use an existential data type (e.g., `data SomeSharedContext = forall s . SomeSC (SharedContext s)`).  I find this a bit more elegant as it doesn't require adopting a continuation passing style.

**Comment by joehendrix** [comment]
One other point with regards to `StableName`: as far as I know, they don't have an `Ord` instance, and they don't expose the comparison operation needed to implement one.

If being able to have an `Ord` instance is important (e.g., for use in `Data.Map`), you'll need to either start mucking around with the internals of `StableName`, or switch to something else (like creating fresh `ForeignPtr`s).

**Comment by brianhuffman** [comment]
We're aware of the lack of an `Ord` instance. They do come with a hash function, though, so instead of `Data.Map`, we'll just switch to a hash map.

**Comment by brianhuffman** [comment]
As far as enforcing consistency goes, eventually we might want to add a certified-term type (#18) that guarantees that a term is well-typed with respect to a particular saw-core module. A type parameter might be useful for that case.
