### ISSUE TITLE
Use nested records and tuples instead of arbitrarily long ones

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/saw-core#6]
If I remember correctly, the idea was to make the current n-ary tuple and record syntax be sugar for a more basic binary nested construct.

**Comment by brianhuffman** [comment]
This was implemented in a series of changesets last September: 051f40d4c79a3e8f8a6f387fa2ded41b91ea8aff, a66ed9f8537ddc88c3e0d4b57ee4f157ae599a8e, 47a445b0c0cc951339165ddc6f62a65f91c69f35, b50d42e370ed2e22e533bb3e3d1867ede0228071, a16b7841675a740442deaddc533926b55402516b, 43085aed514e85bb0b628af03525029c0628728e
