### ISSUE TITLE
What is bvForall used for?

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/saw-core#77]
This primitive seems pretty out of place with the others and has very limited support from the backends.  I don't see any use sites for it, and I'm not sure why it is included.

```
-- Universal quantification over bitvectors
primitive bvForall : (n : Nat) -> (bitvector n -> Bool) -> Bool;
```

**Comment by chameco** [comment]
I think `bvforall` should be completely safe to remove - IIRC it was introduced when we were first playing with arrays of symbolic size in SAW, and has since been superseded by @andreistefanescu 's more recent work.

**Comment by robdockins** [comment]
OK, good to know.

**Comment by robdockins** [comment]
Turns out, Andrei still plans to use this primitive.
