### ISSUE TITLE
External format parser blindly reuses VarIndex values

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/saw-core#94]
https://github.com/GaloisInc/saw-core/blob/066e7a81a0ab3f30fba3c9058dec0a7fc64f88a1/saw-core/src/Verifier/SAW/ExternalFormat.hs#L158

In the above line (and elsewhere in this parser) the VarIndex value that was originally serialized for `ExtCns` values are directly reused when parsed.  This violates the invariant that VarIndex values are always freshly generated from the counter in the `SharedContext`, and could lead to collisions.

**Comment by brianhuffman** [comment]
The case for `Constant` does the exact same thing: https://github.com/GaloisInc/saw-core/blob/066e7a81a0ab3f30fba3c9058dec0a7fc64f88a1/saw-core/src/Verifier/SAW/ExternalFormat.hs#L132

To fix these, I think that when writing external core, the `VarIndex` numbers should just be omitted; then when parsing external core we can just generate fresh `VarIndex`es as needed.

**Comment by robdockins** [comment]
I don't think we can omit the VarIndex until/unless we have some other unique identifier we can use for variables.

**Comment by brianhuffman** [comment]
If there are multiple `Constant`s or `ExtCns`es in the same external core file, then they are distinguished by the `Int` numbering that is used internally within the file. So leaving out the `VarIndex` should work just fine.

**Comment by robdockins** [comment]
I'm not convinced that's enough; there might be `Unshared` terms that contain `ExtCns`, in which case the same `ExtCns` will appear in a rendered file more than once with distinct line numbers, I believe.

**Comment by brianhuffman** [comment]
Yes, I see that unshared `ExtCns` terms would be a problem.

**Comment by brianhuffman** [comment]
Here's probably the cleanest way to fix it: I'll put the `VarIndex`es back into the external core files, but during parsing we'll just maintain another table that maps from old `VarIndex` to new `VarIndex`; whenever we come across a `VarIndex` in the file that we haven't seen before, we'll generate a fresh one using the `SharedContext` and add it to the map.

**Comment by brianhuffman** [comment]
Ok, I closed the old PR and opened a new one with the fix I described above. In the new PR, the pretty printer is completely unchanged, so this should not cause any backward incompatibility with existing external-core files.
